version: '3'

services:
  node:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile-node
    container_name: omnivision_node
    working_dir: /var/app
    volumes:
      - './:/var/app'
    command: 'npm run full:dev'

  nginx:
    image: nginx:alpine
    container_name: omnivision_nginx
    working_dir: /var/app
    ports:
      - '80:8080'
      - '443:8080'
      - '5050:5050'
      - '5051:5051'
      - '5052:5052'
    volumes:
      - './nginx.conf:/etc/nginx/sites-available/default'
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './public:/var/app'
    command: nginx
    depends_on:
      - node
    restart: on-failure
